var searchData=
[
  ['maccess_2ec',['maccess.c',['../maccess_8c.html',1,'']]],
  ['madvise_2ec',['madvise.c',['../madvise_8c.html',1,'']]],
  ['memblock_2ec',['memblock.c',['../memblock_8c.html',1,'']]],
  ['memcontrol_2ec',['memcontrol.c',['../memcontrol_8c.html',1,'']]],
  ['memory_2dfailure_2ec',['memory-failure.c',['../memory-failure_8c.html',1,'']]],
  ['memory_2ec',['memory.c',['../memory_8c.html',1,'']]],
  ['memory_5fhotplug_2ec',['memory_hotplug.c',['../memory__hotplug_8c.html',1,'']]],
  ['mempolicy_2ec',['mempolicy.c',['../mempolicy_8c.html',1,'']]],
  ['mempool_2ec',['mempool.c',['../mempool_8c.html',1,'']]],
  ['memtest_2ec',['memtest.c',['../memtest_8c.html',1,'']]],
  ['migrate_2ec',['migrate.c',['../migrate_8c.html',1,'']]],
  ['mincore_2ec',['mincore.c',['../mincore_8c.html',1,'']]],
  ['mlock_2ec',['mlock.c',['../mlock_8c.html',1,'']]],
  ['mm_5finit_2ec',['mm_init.c',['../mm__init_8c.html',1,'']]],
  ['mmap_2ec',['mmap.c',['../mmap_8c.html',1,'']]],
  ['mmu_5fcontext_2ec',['mmu_context.c',['../mmu__context_8c.html',1,'']]],
  ['mmu_5fnotifier_2ec',['mmu_notifier.c',['../mmu__notifier_8c.html',1,'']]],
  ['mmzone_2ec',['mmzone.c',['../mmzone_8c.html',1,'']]],
  ['mprotect_2ec',['mprotect.c',['../mprotect_8c.html',1,'']]],
  ['mremap_2ec',['mremap.c',['../mremap_8c.html',1,'']]],
  ['msync_2ec',['msync.c',['../msync_8c.html',1,'']]]
];
