var searchData=
[
  ['raid56_2ec',['raid56.c',['../raid56_8c.html',1,'']]],
  ['raid56_2eh',['raid56.h',['../raid56_8h.html',1,'']]],
  ['ram_2ec',['ram.c',['../ram_8c.html',1,'']]],
  ['ram_5fcore_2ec',['ram_core.c',['../ram__core_8c.html',1,'']]],
  ['ramoops_2emod_2ec',['ramoops.mod.c',['../ramoops_8mod_8c.html',1,'']]],
  ['rcom_2ec',['rcom.c',['../rcom_8c.html',1,'']]],
  ['rcom_2eh',['rcom.h',['../rcom_8h.html',1,'']]],
  ['rcu_2dstring_2eh',['rcu-string.h',['../rcu-string_8h.html',1,'']]],
  ['rdwr_2ec',['rdwr.c',['../rdwr_8c.html',1,'']]],
  ['read_2ec',['read.c',['../jffs2_2read_8c.html',1,'(Global Namespace)'],['../nfs_2read_8c.html',1,'(Global Namespace)']]],
  ['read_5fwrite_2ec',['read_write.c',['../ecryptfs_2read__write_8c.html',1,'(Global Namespace)'],['../read__write_8c.html',1,'(Global Namespace)']]],
  ['reada_2ec',['reada.c',['../reada_8c.html',1,'']]],
  ['readdir_2ec',['readdir.c',['../cifs_2readdir_8c.html',1,'(Global Namespace)'],['../overlayfs_2readdir_8c.html',1,'(Global Namespace)'],['../readdir_8c.html',1,'(Global Namespace)']]],
  ['readinode_2ec',['readinode.c',['../readinode_8c.html',1,'']]],
  ['readpage_2ec',['readpage.c',['../readpage_8c.html',1,'']]],
  ['recover_2ec',['recover.c',['../recover_8c.html',1,'']]],
  ['recover_2eh',['recover.h',['../recover_8h.html',1,'']]],
  ['recoverd_2ec',['recoverd.c',['../recoverd_8c.html',1,'']]],
  ['recoverd_2eh',['recoverd.h',['../recoverd_8h.html',1,'']]],
  ['recovery_2ec',['recovery.c',['../f2fs_2recovery_8c.html',1,'(Global Namespace)'],['../gfs2_2recovery_8c.html',1,'(Global Namespace)'],['../jbd2_2recovery_8c.html',1,'(Global Namespace)'],['../nilfs2_2recovery_8c.html',1,'(Global Namespace)'],['../ubifs_2recovery_8c.html',1,'(Global Namespace)']]],
  ['recovery_2eh',['recovery.h',['../recovery_8h.html',1,'']]],
  ['ref_2dverify_2ec',['ref-verify.c',['../ref-verify_8c.html',1,'']]],
  ['ref_2dverify_2eh',['ref-verify.h',['../ref-verify_8h.html',1,'']]],
  ['refcount_2ec',['refcount.c',['../refcount_8c.html',1,'']]],
  ['refcounttree_2ec',['refcounttree.c',['../refcounttree_8c.html',1,'']]],
  ['refcounttree_2eh',['refcounttree.h',['../refcounttree_8h.html',1,'']]],
  ['reiserfs_2eh',['reiserfs.h',['../reiserfs_8h.html',1,'']]],
  ['reiserfs_2emod_2ec',['reiserfs.mod.c',['../reiserfs_8mod_8c.html',1,'']]],
  ['relocation_2ec',['relocation.c',['../relocation_8c.html',1,'']]],
  ['replay_2ec',['replay.c',['../replay_8c.html',1,'']]],
  ['requestqueue_2ec',['requestqueue.c',['../requestqueue_8c.html',1,'']]],
  ['requestqueue_2eh',['requestqueue.h',['../requestqueue_8h.html',1,'']]],
  ['reservations_2ec',['reservations.c',['../reservations_8c.html',1,'']]],
  ['reservations_2eh',['reservations.h',['../reservations_8h.html',1,'']]],
  ['resize_2ec',['resize.c',['../ext4_2resize_8c.html',1,'(Global Namespace)'],['../jfs_2resize_8c.html',1,'(Global Namespace)'],['../ocfs2_2resize_8c.html',1,'(Global Namespace)'],['../reiserfs_2resize_8c.html',1,'(Global Namespace)']]],
  ['resize_2eh',['resize.h',['../resize_8h.html',1,'']]],
  ['revoke_2ec',['revoke.c',['../revoke_8c.html',1,'']]],
  ['rfc1002pdu_2eh',['rfc1002pdu.h',['../rfc1002pdu_8h.html',1,'']]],
  ['rgrp_2ec',['rgrp.c',['../rgrp_8c.html',1,'']]],
  ['rgrp_2eh',['rgrp.h',['../rgrp_8h.html',1,'']]],
  ['rmap_2ec',['rmap.c',['../rmap_8c.html',1,'']]],
  ['rock_2ec',['rock.c',['../rock_8c.html',1,'']]],
  ['rock_2eh',['rock.h',['../rock_8h.html',1,'']]],
  ['romfs_2emod_2ec',['romfs.mod.c',['../romfs_8mod_8c.html',1,'']]],
  ['root_2dtree_2ec',['root-tree.c',['../root-tree_8c.html',1,'']]],
  ['root_2ec',['root.c',['../autofs4_2root_8c.html',1,'(Global Namespace)'],['../proc_2root_8c.html',1,'(Global Namespace)']]],
  ['rotate_2ec',['rotate.c',['../rotate_8c.html',1,'']]],
  ['rpc_5fpipefs_2ec',['rpc_pipefs.c',['../rpc__pipefs_8c.html',1,'']]],
  ['rtbitmap_2ec',['rtbitmap.c',['../rtbitmap_8c.html',1,'']]],
  ['runlist_2ec',['runlist.c',['../runlist_8c.html',1,'']]],
  ['runlist_2eh',['runlist.h',['../runlist_8h.html',1,'']]],
  ['rxrpc_2ec',['rxrpc.c',['../rxrpc_8c.html',1,'']]]
];
