var searchData=
[
  ['cache_2ec',['cache.c',['../9p_2cache_8c.html',1,'(Global Namespace)'],['../afs_2cache_8c.html',1,'(Global Namespace)'],['../ceph_2cache_8c.html',1,'(Global Namespace)'],['../cifs_2cache_8c.html',1,'(Global Namespace)'],['../coda_2cache_8c.html',1,'(Global Namespace)'],['../fat_2cache_8c.html',1,'(Global Namespace)'],['../fscache_2cache_8c.html',1,'(Global Namespace)'],['../squashfs_2cache_8c.html',1,'(Global Namespace)']]],
  ['cache_2eh',['cache.h',['../9p_2cache_8h.html',1,'(Global Namespace)'],['../ceph_2cache_8h.html',1,'(Global Namespace)'],['../nfsd_2cache_8h.html',1,'(Global Namespace)']]],
  ['cache_5flib_2ec',['cache_lib.c',['../cache__lib_8c.html',1,'']]],
  ['cache_5flib_2eh',['cache_lib.h',['../cache__lib_8h.html',1,'']]],
  ['cachefiles_2emod_2ec',['cachefiles.mod.c',['../cachefiles_8mod_8c.html',1,'']]],
  ['callback_2ec',['callback.c',['../afs_2callback_8c.html',1,'(Global Namespace)'],['../nfs_2callback_8c.html',1,'(Global Namespace)']]],
  ['callback_2eh',['callback.h',['../callback_8h.html',1,'']]],
  ['callback_5fproc_2ec',['callback_proc.c',['../callback__proc_8c.html',1,'']]],
  ['callback_5fxdr_2ec',['callback_xdr.c',['../callback__xdr_8c.html',1,'']]],
  ['caps_2ec',['caps.c',['../caps_8c.html',1,'']]],
  ['catalog_2ec',['catalog.c',['../catalog_8c.html',1,'(Global Namespace)'],['../lus_2catalog_8c.html',1,'(Global Namespace)']]],
  ['cell_2ec',['cell.c',['../cell_8c.html',1,'']]],
  ['ceph_2emod_2ec',['ceph.mod.c',['../ceph_8mod_8c.html',1,'']]],
  ['ceph_5ffrag_2ec',['ceph_frag.c',['../ceph__frag_8c.html',1,'']]],
  ['char_5fdev_2ec',['char_dev.c',['../char__dev_8c.html',1,'']]],
  ['check_2dintegrity_2ec',['check-integrity.c',['../check-integrity_8c.html',1,'']]],
  ['check_2dintegrity_2eh',['check-integrity.h',['../check-integrity_8h.html',1,'']]],
  ['checkpoint_2ec',['checkpoint.c',['../f2fs_2checkpoint_8c.html',1,'(Global Namespace)'],['../jbd2_2checkpoint_8c.html',1,'(Global Namespace)']]],
  ['cifs_2emod_2ec',['cifs.mod.c',['../cifs_8mod_8c.html',1,'']]],
  ['cifs_5fdebug_2ec',['cifs_debug.c',['../cifs__debug_8c.html',1,'']]],
  ['cifs_5fdebug_2eh',['cifs_debug.h',['../cifs__debug_8h.html',1,'']]],
  ['cifs_5fdfs_5fref_2ec',['cifs_dfs_ref.c',['../cifs__dfs__ref_8c.html',1,'']]],
  ['cifs_5ffs_5fsb_2eh',['cifs_fs_sb.h',['../cifs__fs__sb_8h.html',1,'']]],
  ['cifs_5fioctl_2eh',['cifs_ioctl.h',['../cifs__ioctl_8h.html',1,'']]],
  ['cifs_5fspnego_2ec',['cifs_spnego.c',['../cifs__spnego_8c.html',1,'']]],
  ['cifs_5fspnego_2eh',['cifs_spnego.h',['../cifs__spnego_8h.html',1,'']]],
  ['cifs_5funicode_2ec',['cifs_unicode.c',['../cifs__unicode_8c.html',1,'']]],
  ['cifs_5funicode_2eh',['cifs_unicode.h',['../cifs__unicode_8h.html',1,'']]],
  ['cifs_5funiupr_2eh',['cifs_uniupr.h',['../cifs__uniupr_8h.html',1,'']]],
  ['cifsacl_2ec',['cifsacl.c',['../cifsacl_8c.html',1,'']]],
  ['cifsacl_2eh',['cifsacl.h',['../cifsacl_8h.html',1,'']]],
  ['cifsencrypt_2ec',['cifsencrypt.c',['../cifsencrypt_8c.html',1,'']]],
  ['cifsfs_2ec',['cifsfs.c',['../cifsfs_8c.html',1,'']]],
  ['cifsfs_2eh',['cifsfs.h',['../cifsfs_8h.html',1,'']]],
  ['cifsglob_2eh',['cifsglob.h',['../cifsglob_8h.html',1,'']]],
  ['cifspdu_2eh',['cifspdu.h',['../cifspdu_8h.html',1,'']]],
  ['cifsproto_2eh',['cifsproto.h',['../cifsproto_8h.html',1,'']]],
  ['cifssmb_2ec',['cifssmb.c',['../cifssmb_8c.html',1,'']]],
  ['client_2ec',['client.c',['../client_8c.html',1,'']]],
  ['clnt4xdr_2ec',['clnt4xdr.c',['../clnt4xdr_8c.html',1,'']]],
  ['clntlock_2ec',['clntlock.c',['../clntlock_8c.html',1,'']]],
  ['clntproc_2ec',['clntproc.c',['../clntproc_8c.html',1,'']]],
  ['clntxdr_2ec',['clntxdr.c',['../clntxdr_8c.html',1,'']]],
  ['cmdline_2ec',['cmdline.c',['../cmdline_8c.html',1,'']]],
  ['cmservice_2ec',['cmservice.c',['../cmservice_8c.html',1,'']]],
  ['cnode_2ec',['cnode.c',['../cnode_8c.html',1,'']]],
  ['coda_2emod_2ec',['coda.mod.c',['../coda_8mod_8c.html',1,'']]],
  ['coda_5fcache_2eh',['coda_cache.h',['../coda__cache_8h.html',1,'']]],
  ['coda_5ffs_5fi_2eh',['coda_fs_i.h',['../coda__fs__i_8h.html',1,'']]],
  ['coda_5fint_2eh',['coda_int.h',['../coda__int_8h.html',1,'']]],
  ['coda_5flinux_2ec',['coda_linux.c',['../coda__linux_8c.html',1,'']]],
  ['coda_5flinux_2eh',['coda_linux.h',['../coda__linux_8h.html',1,'']]],
  ['collate_2ec',['collate.c',['../collate_8c.html',1,'']]],
  ['collate_2eh',['collate.h',['../collate_8h.html',1,'']]],
  ['commit_2ec',['commit.c',['../jbd2_2commit_8c.html',1,'(Global Namespace)'],['../ubifs_2commit_8c.html',1,'(Global Namespace)']]],
  ['common_2ec',['common.c',['../common_8c.html',1,'']]],
  ['common_2eh',['common.h',['../exofs_2common_8h.html',1,'(Global Namespace)'],['../xfs_2scrub_2common_8h.html',1,'(Global Namespace)']]],
  ['compat_2ec',['compat.c',['../compat_8c.html',1,'(Global Namespace)'],['../quota_2compat_8c.html',1,'(Global Namespace)']]],
  ['compat_5fbinfmt_5felf_2ec',['compat_binfmt_elf.c',['../compat__binfmt__elf_8c.html',1,'']]],
  ['compat_5fioctl_2ec',['compat_ioctl.c',['../compat__ioctl_8c.html',1,'']]],
  ['compr_2ec',['compr.c',['../compr_8c.html',1,'']]],
  ['compr_2eh',['compr.h',['../compr_8h.html',1,'']]],
  ['compr_5flzo_2ec',['compr_lzo.c',['../compr__lzo_8c.html',1,'']]],
  ['compr_5frtime_2ec',['compr_rtime.c',['../compr__rtime_8c.html',1,'']]],
  ['compr_5frubin_2ec',['compr_rubin.c',['../compr__rubin_8c.html',1,'']]],
  ['compr_5fzlib_2ec',['compr_zlib.c',['../compr__zlib_8c.html',1,'']]],
  ['compress_2ec',['compress.c',['../isofs_2compress_8c.html',1,'(Global Namespace)'],['../ntfs_2compress_8c.html',1,'(Global Namespace)'],['../ubifs_2compress_8c.html',1,'(Global Namespace)']]],
  ['compression_2ec',['compression.c',['../compression_8c.html',1,'']]],
  ['compression_2eh',['compression.h',['../compression_8h.html',1,'']]],
  ['config_2ec',['config.c',['../config_8c.html',1,'']]],
  ['config_2eh',['config.h',['../config_8h.html',1,'']]],
  ['configfs_5finternal_2eh',['configfs_internal.h',['../configfs__internal_8h.html',1,'']]],
  ['connect_2ec',['connect.c',['../connect_8c.html',1,'']]],
  ['consoles_2ec',['consoles.c',['../consoles_8c.html',1,'']]],
  ['control_2ec',['control.c',['../control_8c.html',1,'']]],
  ['cookie_2ec',['cookie.c',['../cookie_8c.html',1,'']]],
  ['copy_5fup_2ec',['copy_up.c',['../copy__up_8c.html',1,'']]],
  ['coredump_2ec',['coredump.c',['../coredump_8c.html',1,'']]],
  ['cpfile_2ec',['cpfile.c',['../cpfile_8c.html',1,'']]],
  ['cpfile_2eh',['cpfile.h',['../cpfile_8h.html',1,'']]],
  ['cpuinfo_2ec',['cpuinfo.c',['../cpuinfo_8c.html',1,'']]],
  ['cramfs_2emod_2ec',['cramfs.mod.c',['../cramfs_8mod_8c.html',1,'']]],
  ['crypto_2ec',['crypto.c',['../crypto_2crypto_8c.html',1,'(Global Namespace)'],['../ecryptfs_2crypto_8c.html',1,'(Global Namespace)'],['../ubifs_2crypto_8c.html',1,'(Global Namespace)']]],
  ['ctree_2ec',['ctree.c',['../ctree_8c.html',1,'']]],
  ['ctree_2eh',['ctree.h',['../ctree_8h.html',1,'']]],
  ['current_5fstateid_2eh',['current_stateid.h',['../current__stateid_8h.html',1,'']]],
  ['cuse_2ec',['cuse.c',['../cuse_8c.html',1,'']]],
  ['cuse_2emod_2ec',['cuse.mod.c',['../cuse_8mod_8c.html',1,'']]],
  ['cylinder_2ec',['cylinder.c',['../cylinder_8c.html',1,'']]]
];
