var dir_dc33d15fc61ff69482cd80629bb1c789 =
[
    [ "acl.c", "orangefs_2acl_8c.html", "orangefs_2acl_8c" ],
    [ "dcache.c", "orangefs_2dcache_8c.html", "orangefs_2dcache_8c" ],
    [ "devorangefs-req.c", "devorangefs-req_8c.html", "devorangefs-req_8c" ],
    [ "dir.c", "orangefs_2dir_8c.html", "orangefs_2dir_8c" ],
    [ "downcall.h", "downcall_8h.html", "downcall_8h" ],
    [ "file.c", "orangefs_2file_8c.html", "orangefs_2file_8c" ],
    [ "inode.c", "orangefs_2inode_8c.html", "orangefs_2inode_8c" ],
    [ "namei.c", "orangefs_2namei_8c.html", "orangefs_2namei_8c" ],
    [ "orangefs-bufmap.c", "orangefs-bufmap_8c.html", "orangefs-bufmap_8c" ],
    [ "orangefs-bufmap.h", "orangefs-bufmap_8h.html", "orangefs-bufmap_8h" ],
    [ "orangefs-cache.c", "orangefs-cache_8c.html", "orangefs-cache_8c" ],
    [ "orangefs-debug.h", "orangefs-debug_8h.html", "orangefs-debug_8h" ],
    [ "orangefs-debugfs.c", "orangefs-debugfs_8c.html", "orangefs-debugfs_8c" ],
    [ "orangefs-debugfs.h", "orangefs-debugfs_8h.html", "orangefs-debugfs_8h" ],
    [ "orangefs-dev-proto.h", "orangefs-dev-proto_8h.html", "orangefs-dev-proto_8h" ],
    [ "orangefs-kernel.h", "orangefs-kernel_8h.html", "orangefs-kernel_8h" ],
    [ "orangefs-mod.c", "orangefs-mod_8c.html", "orangefs-mod_8c" ],
    [ "orangefs-sysfs.c", "orangefs-sysfs_8c.html", "orangefs-sysfs_8c" ],
    [ "orangefs-sysfs.h", "orangefs-sysfs_8h.html", "orangefs-sysfs_8h" ],
    [ "orangefs-utils.c", "orangefs-utils_8c.html", "orangefs-utils_8c" ],
    [ "orangefs.mod.c", "orangefs_8mod_8c.html", "orangefs_8mod_8c" ],
    [ "protocol.h", "protocol_8h.html", "protocol_8h" ],
    [ "super.c", "orangefs_2super_8c.html", "orangefs_2super_8c" ],
    [ "symlink.c", "orangefs_2symlink_8c.html", "orangefs_2symlink_8c" ],
    [ "upcall.h", "upcall_8h.html", "upcall_8h" ],
    [ "waitqueue.c", "waitqueue_8c.html", "waitqueue_8c" ],
    [ "xattr.c", "orangefs_2xattr_8c.html", "orangefs_2xattr_8c" ]
];